[package]
name = "ukmm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
dircpy = "0.3.12"
dirs2 = "3.0.1"
env_logger = "0.9.0"
fs-err = "2.8.1"
jwalk = "0.6.0"
join_str = "0.1.0"
log = "0.4.17"
once_cell = "1.13.1"
parking_lot = "0.12.1"
rayon = "1.5.3"
roead = "0.16.0"
rustc-hash = "1.1.0"
rstb = { version= "0.3.2", features = ["botw-data"] }
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_yaml = "0.9.10"
smartstring = { version = "1.0.1", features = ["serde"] }
toml = "0.5.9"
uk-content = { path = "./uk-content" }
uk-mod = { path = "./uk-mod" }
uk-reader = { path = "./uk-reader" }
zip = { version = "0.6.2", default-features = false, features = ["deflate"]}

[target.'cfg(windows)'.dependencies]
remove_dir_all = "0.7.0"

[workspace]
members = [
    "uk-content",
    "uk-mod",
    "uk-reader",
]

[profile.dev]
opt-level = 2
