newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Unstable features below
unstable_features = true
version = "Two"
comment_width = 100
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
wrap_comments = true
reorder_impl_items = true
struct_field_align_threshold = 4
force_multiline_blocks = true
overflow_delimited_expr = true