[package]
name = "uk-content"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
indexmap = { workspace = true }
join_str = { workspace = true }
minicbor-ser = { workspace = true }
roead = { workspace = true, features = ["with-serde"] }
rustc-hash = { workspace = true }
rstb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smartstring = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
zstd = { workspace = true }

itertools = "0.10.3"
lexical = "6.1.1"
lexical-core = "0.8.5"
lighter = "0.1.0"
mimalloc = { version = "0.1.30", default-features = false }
msyt = { git = "https://github.com/NiceneNerd/msyt", rev = "12e4d95fb6480f445284f37706db7bfa8351dc06" }
uk-content-derive = { path = "../uk-content-derive" }
uk-ui = { path = "../uk-ui", optional = true }
uk-ui-derive = { path = "../uk-ui-derive", optional = true }

[features]
ui = ["uk-ui", "uk-ui-derive", "roead/yaml"]
