[package]
name = "uk-content-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.14.2"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }